### ISSUE TITLE
Week 8 and Week 9 : Experiments almost same 

### ISSUE THREAD

**Issue by rishi11** [abhishek10/CS5610-abhik#4]
Your experiments should show the gradual increase in your learning. Your experiments during Week 8 and Week 9 are identical. Please change the experiments to implement some other functionality and to show gradual increase in learning.

**Comment by abhishek10** [comment]
Hi Rishi,

This experiments are related to project. My project is to search events all over the world using eventful api. In my week-9 experiments, I searched for the api, I obtained the permission from the api providing company and now in my experiments I am calling this external web API to fetch the data related to particular event.
In week-8 assignment there is nothing related to web API and it was related to graphics.

Though UI of week-9 experiments is not that great, what is great about those experiments is, I spent lot of time on how to call those API and get response from it and parse that response.

Please let me know what do you mean by experiments are identical.

Thanks,
Abhishek
